In [1]:
import numpy as np

In [2]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [3]:
lst1 = []
lst2 = []
for i in range(5):
    num1 = int(input())
    lst1.append(num1)
print("LIST1:",lst1)

for i in range(5):
    num2 = int(input())
    lst2.append(num2)
print("LIST2:",lst2)

1
2
3
4
5
LIST1: [1, 2, 3, 4, 5]
2
3
4
5
6
LIST2: [2, 3, 4, 5, 6]


In [6]:
#convert to array
my_list1 = np.array(lst1)
my_list2 = np.array(lst2)
print("list to array conversion1:",my_list1)
print("list to array conversion2:",my_list2)

list to array conversion1: [1 2 3 4 5]
list to array conversion2: [2 3 4 5 6]


In [7]:
#concatination of array
array_concat = np.concatenate((my_list1,my_list2))
print("concatination of two arrays is:",array_concat)

concatination of two arrays is: [1 2 3 4 5 2 3 4 5 6]


In [8]:
#sorting of array
sorted_array = np.sort(array_concat)

In [9]:
print("sorted array is:",sorted_array)

sorted array is: [1 2 2 3 3 4 4 5 5 6]


In [11]:
array_one = np.array([[1,2,3],[5,6,7],[8,7,6]])
print("dimensions of a ndarray is:",array_one.ndim)
print("size of an ndarray is:",array_one.size)

dimensions of a ndarray is: 2
size of an ndarray is: 9


In [12]:
arr = np.arange(int(input()))
print("Test 1D array (shape):",arr.shape)

2
Test 1D array (shape): (2,)


In [13]:
two_D_array_row = arr[np.newaxis]
print("Test 2D array:",two_D_array_row.shape)

Test 2D array: (1, 2)


In [14]:
two_D_array_col = arr[:,np.newaxis]
print("Test 2D array:",two_D_array_col.shape)

Test 2D array: (2, 1)


# OR

In [15]:
a = np.array([2, 4])
b = np.expand_dims(a, axis=1)
print(b)

[[2]
 [4]]


In [16]:
b.shape

(2, 1)

In [17]:
stack_1 = np.square([1,2,3,4,5,])
stack_2 = np.square([6,7,8,9,10])
print("vertical stack is:",np.vstack((stack_1,stack_2)))
print("horizontal stack is:",np.hstack((stack_1,stack_2)))

vertical stack is: [[  1   4   9  16  25]
 [ 36  49  64  81 100]]
horizontal stack is: [  1   4   9  16  25  36  49  64  81 100]


In [18]:
array_1 = np.array([1,2,3,1,2,2,5,8,8,5,9,7,9,7,6,5])
unique, counts = np.unique(array_1,return_counts=True)
array_1= np.asarray((unique, counts)).T
print(array_1)

[[1 2]
 [2 3]
 [3 1]
 [5 3]
 [6 1]
 [7 2]
 [8 2]
 [9 2]]
